### PR TITLE
Propose ADR for removing file header comments

### PR DESCRIPTION
**Pull request by joshuatbrown**
File header comments annoy me. I suggest we remove them.

### CODE REVIEW

**Review by mplorentz — COMMENTED** [review]
I'm fine with this. I'm wary of creating more work here but it seems like this would be even better as a swiftlint rule. I wonder if one exists...

It looks like there is a `file_header` rule. Here's a git patch that will make it generate a warning for file headers:
```
diff --git a/.swiftlint.yml b/.swiftlint.yml
index 9830c814f..2265ab878 100644
--- a/.swiftlint.yml
+++ b/.swiftlint.yml
@@ -30,6 +30,7 @@ opt_in_rules: # some rules are turned off by default, so you need to opt-in
   - empty_string
   - enum_case_associated_values_count
   - fatal_error_message
+  - file_header
   - first_where
   - flatmap_over_map_reduce
   - force_unwrapping
@@ -157,3 +158,6 @@ number_separator:
 cyclomatic_complexity:
   ignores_case_statements: true
 reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
+
+file_header:
+  forbidden_pattern: ".?"
```

@joshuatbrown what do you think of this approach?

**Comment by joshuatbrown** [comment]
@mplorentz that's awesome! I'm all for it!

**Comment by martindsq** [comment]
I'm totally fine with this. The information in headers is useless.
I wonder if file_header rule triggers when the first thing is a doc comment about the first structure. Lilke

```
/// This is what this structs does
struct MyStruct {}
```

and I wonder what happens if we include a file from a 3rd party in the code.

**Comment by mplorentz** [comment]
> I wonder if file_header rule triggers when the first thing is a doc comment about the first structure. 

It doesn't! I tested

> and I wonder what happens if we include a file from a 3rd party in the code.

Swiftlint doesn't run on imported Swift packages, but if we copy/paste a file into our main target we will need to remove the header or stick a `// swiftlint:disable` directive in there. (I'm assuming it won't treat `swiftlint:disable` as a header comment, it should evaluate those before evaluating rules).

**Review by martindsq — APPROVED** [review]
I'm approving this because I think it's good to have this.

We should not be removing the header when including 3rd party code as sometimes it contains the copyright notice, we should add the skip rule line instead. I was thinking about the Starscream code we used to have. I'm glad we don't have it anymore :).

**Comment by joshuatbrown** [comment]
@mplorentz Are you suggesting I add the swiftlint rule in this PR? If so, I'd suggest we do that in a separate PR so we can keep ADR PRs purely focused on the proposal without any implementation details.

**Comment by mplorentz** [comment]
@joshuatbrown I'm actually suggesting we do a swiftlint rule _instead_ of this ADR. Swiftlint is already documenting our agreed upon syntax conventions, and this fits right in there.

**Comment by joshuatbrown** [comment]
@mplorentz ahhhhh, well then I agree 100% with you. Thanks for clarifying!

**Comment by martindsq** [comment]
@joshuatbrown this article explains how to change the header. In can be a user thing, or a project-wide thing.

**Comment by joshuatbrown** [comment]
See #952, which supersedes this.

**Pull request closed without merging**
