### PR TITLE
Remove SwiftGenPlugin and XCStringsToolPlugin

### PR DESCRIPTION
**Pull request by joshuatbrown**
## Issues covered
#1117 

## Update June 25, 12:05 PM Eastern
The SwiftUI Previews build now works on its own! To verify:

1. Clean
2. Open a view with a preview, such as AboutView

It should build and show you a preview. It should also show around 832 warnings, all of which I guess were hidden when XCStringsToolPlugin was a plugin? I have a few things I'd still like to do:

- [ ] make SwiftGen output Assets.generated.swift instead of AssetsGenerated
- [x] make sure xcstringstool is all good with paths and script
- [ ] move script for SwiftGen from Xcode build phase into Scripts/
- [ ] move script for xcstrings-tool from Xcode build phase into Scripts/
- [x] should we move folders for tools into Scripts? probably
- [ ] fix warnings (how were these ignored before?)
- [x] ignore all Generated files in SwiftLint (why isn’t it already?) Localizable.generated shows line length, nesting, other violations
- [ ] consider using input files in Xcode so it doesn’t run xcstrings-tool every time (also re-check Based on dependency analysis)
- [ ] remove binary for SwiftGen
- [ ] remove binary for XCStringsTool (whoops!)
- [ ] squash commits

## Description
In the hope that this'll fix our build issue with SwiftGen previews, I've removed SwiftGenPlugin and replaced it with the SwiftGen binary. I also added the [SwiftGen-generated file](https://github.com/planetary-social/nos/pull/1261/files#diff-2b28627243162066459074ff0cd9c55482c576e4e18a3fb04b917affbd3a4066) to our repo since Matt and I discussed that (and since the other way just wouldn't compile for me).

Unfortunately, I still get errors like the following, which is the first of many:

```
== PREVIEW UPDATE ERROR:

    SchemeBuildError: Failed to build the scheme “Nos”
    
    type 'LocalizedStringResource' has no member 'moderation'
    
    Emitting module for NosTests:
    /Users/josh/Code/nos/Nos/Models/ReportCategory.swift:50:16: error: type 'LocalizedStringResource' has no member 'moderation'
            name: .moderation.coarseLanguage,
                  ~^~~~~~~~~~
```

I'm afraid this means that there's not an issue with SwiftGenPlugin; there's an issue with Xcode where using any plugin will cause the Preview build to fail. I'd love to be proven wrong, though, so please give it a shot.

## How to test
1. Clean and
4. Navigate to AboutView
5. Click the Refresh button on the Preview
6. Observe Preview

Ideally, the Preview would appear. However, at this point, the Preview build is still failing so you'll see a failure, and if you click the Diagnostics button you'll see the error above.

## Conclusion
I think that in order to get SwiftUI Previews to work when building them (and not require the dev to build the Test target), we have to remove both Swift Package Plugins. That would probably mean we need to either:

1. Use SwiftGen to generate the localization constants
2. Find a new tool to generate localization constants

In my brief search, neither seemed straightforward or simple. SwiftGen's documentation talks about generating code from `.strings` files, not `.xcstrings` files like we're using. Maybe someone out there has created a stencil for it, though.

I searched a bit for another tool, but all I found was the tool we're currently using: `XCStringsToolPlugin`.

### CODE REVIEW

**Review by mplorentz — COMMENTED** [review]
I'm seeing the same error as you in Xcode 15.3 and 15.4. I also tried Xcode 16 beta 1 and got a different error, but the preview build succeeded so I think maybe xcstringstool is working there 🤔
```
== PREVIEW UPDATE ERROR:

    FailedToLaunchAppError: Failed to launch com.verse.Nos-dev
    
    ==================================
    
    |  [Remote] JITError
    |  
    |  ==================================
    |  
    |  |  [Remote] LLVMError
    |  |  
    |  |  LLVMError: LLVMError(description: "The file was not recognized as a valid object file")
``` 

Then I went back and tried Xcode 15.2. To my surprise, after fixing a compile error (?) the preview worked!

I also saw that the xcstringstool dev is wanting to help and [shared](https://github.com/liamnichols/xcstrings-tool/issues/32#issuecomment-2188760055) a cli command that we might be able to put in a bash script. 

I think there are a number of paths forward here (from easiest to hardest):
- should we just deal with having to build for testing?
- should we just downgrade to Xcode 15.2 until Xcode 16 is released in the fall?
- should we try to remove the xcstringstool build plugin and use the command-line version until Xcode 16 is released in the fall. If it was temporary I would be ok with just copying the xcstringstool source code into our Scripts folder.

**Comment by mplorentz** [comment]
I pushed my source changes for Xcode 15.2 up to `xcode-15.2-again` in case you want to play with them.

**Comment by joshuatbrown** [comment]
@mplorentz I'm willing to spend some time this morning removing the XCStringsTool build plugin and switching to the command-line version to see if that works in Xcode 15.3. If not, I'm willing to consider the downgrade to Xcode 15.2 or just dealing with doing a build for testing to get Previews to work.

**Review by mplorentz — CHANGES_REQUESTED** [review]
I like this approach! I think it's going to work. The previews compiled the first time for me after a clean.

I don't like having the binaries for SwiftGen and xcstringstool in the git repo though. In fact, I think we should squash these commits before merging to make sure we don't forever add a 42MB blob to our repo. Ideally we would add instructions to install them with `brew` in the `README.md` or `CONTRIBUTING.md`. But xcstringstool isn't in brew. We could copy the source code in here and execute it as a swift script, or we could put the binary in git-lfs. Any of these are fine with me.

I don't think we need all those SwiftGen stencils either. I think the only one we need is in `Nos/Assets/SwiftGen Stencils`?

**Comment by joshuatbrown** [comment]
I 100% agree that adding a 42MB blob to the repo isn't ideal, so let's not do that.

I've used git-lfs on a previous project, and it was just a pain. It's an extra thing for developers to do when cloning, and it's just this little annoyance that's always there. Maybe the real issue there was that new people were frequently added to the team, I was constantly supporting them, and people failed to read the docs. Although we don't frequently add new devs here, git-lfs would be one more thing for them to do.

I tried just copying the source over and running that. It's totally doable on the command line, but getting it to run in Xcode has thus far been an insurmountable challenge. It's a Swift package with an executable target, so you can easily run it with `swift run xcstrings-tool` -- as long as you're inside the `xcstrings-tool` folder that contains its `Package.swift` file. If you're not inside that folder, as is the case when running a Nos build of any kind (plain, Previews, Testing), it doesn't seem possible to run it. I tried starting the command with `cd xcstrings-tool-0.5.1; swift run xcstrings-tool ...` but then execution fails with the following:

```
error: fatalError
<unknown>:0: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX'
<unknown>:0: error: unable to load standard library for target 'arm64-apple-macosx13.0'
```

So now we're in an iPhoneSimulator build and we want to create and run a MacOSX executable. I'm running out of ideas, and feeling like I've spent nearly enough time on this for now.

Personally, I'm ready to go back to one of the easier options you suggested:

> should we just deal with having to build for testing?
> should we just downgrade to Xcode 15.2 until Xcode 16 is released in the fall?

**Comment by joshuatbrown** [comment]
I just checked and Xcode 15.2 also works for me. I'm not sure I'd want to downgrade, though. For me, the simplest solution -- dealing with having to build for testing -- works just fine.

**Comment by mplorentz** [comment]
Our repository is actually already set up with git lfs, but I looked and we aren't currently tracking any files in lfs - I think they must have been deleted at some point. 

Personally I'd rather go back to Xcode 15.2 - what are we even losing? I was able to build and deploy to my iOS 17.5 device from Xcode 15.2, maybe because I have the toolchain from 15.3 (and 4?). But maybe we don't even all need to downgrade. Some people can stay on 15.3 and build for testing and others can go to 15.2? 

I tested 15.2 with this branch. Should we go ahead and merge the SwiftGen parts? I just don't trust Apple to continue supporting build plugins in a reasonable way - even if they did fix this one issue in Xcode 16 beta 1.

**Comment by martindsq** [comment]
Relevant discussion on SwiftGen: https://github.com/SwiftGen/SwiftGen/issues/1065 
It seems we will have to wait until we have string catalog support.

If it were just me, I'm fine not using a tool for generating an enum with localized strings and just use the normal way. But I'm aware not everyone is a fan of minimalism there xd

I think using SwiftGen would be the best of both worlds, but given that we cannot do that already, what about considering a second time this suggestion by Matt:

> should we try to remove the xcstringstool build plugin and use the command-line version until Xcode 16 is released in the fall. If it was temporary I would be ok with just copying the xcstringstool source code into our Scripts folder.

That would mean that xcstringstool is not required for no-one (unless you want to add a new localized string) and we would have to run the script just when we update the asset catalog, which doesn't happen very often.

**Comment by joshuatbrown** [comment]
Since we merged #1265, we're moving forward with Xcode 15.2 and don't need what's in this PR. We concluded that Xcode 15.2 is the best approach for Previews right now, since removing XCStringsToolPlugin in particular has proven difficult.

**Pull request closed without merging**
