### PR TITLE
Fix translations

### PR DESCRIPTION
**Pull request by mplorentz**
This fixes a couple of translations that weren't showing up because I added them in Crowdin but not in Xcode. I also moved the Terms of Service out of the strings file for legal reasons.

### CODE REVIEW

**Comment by martindsq** [comment]
The french and chinese corrections are fine. However, I missed when you added brazilian portuguese to the project. That one is not included in the list of languages, but it is in the project if you look in Finder.
We need to correct that, but as we are in that, I'd like to correct it to just portuguese (pt), not brazilian portuguese which is too specific. In order to do that, we need to add a mapping like we do in planetary: https://github.com/planetary-social/planetary-ios/blob/main/crowdin.yml

**Comment by mplorentz** [comment]
@martindsq 
> That one is not included in the list of languages, but it is in the project if you look in Finder
What list of languages are you talking about?

> I'd like to correct it to just portuguese (pt), not brazilian portuguese which is too specific.
I asked the volunteer who wanted to translate Brazilian Portuguese if she could do Portuguese instead, and she said they are different enough that it didn't make sense to do that. I don't know Portuguese so I was deferring to her. I think if that's how she feels it doesn't make sense to force her to translate Portuguese (or as she called it, European Portuguese). Is that ok with you?

**Comment by martindsq** [comment]
> What list of languages are you talking about?

If you head to the Info tab inside Nos project (not the target) you can see the list of languages and add a new one. This change will be reflected in the translated languages of Generated.strings file, right now it doesn't appear if you expand the file.

> > I'd like to correct it to just portuguese (pt), not brazilian portuguese which is too specific.
> 
> I asked the volunteer who wanted to translate Brazilian Portuguese if she could do Portuguese instead, and she said they are different enough that it didn't make sense to do that. I don't know Portuguese so I was deferring to her. I think if that's how she feels it doesn't make sense to force her to translate Portuguese (or as she called it, European Portuguese). Is that ok with you?

I agree with not forcing here to translate Portuguese, and also agree with relying on her to decide this. I'd like to ask her if brazilian portuguese could work for portuguese until we have a specific translation for portugal or they are indeed very different and could cause a confusion, in this case we proceed with brazilian portuguese.

**Comment by martindsq** [comment]
My worry is that we are preventing non-brazilian portuguese people from having a translation that could work for them in the mean time.

**Comment by mplorentz** [comment]
@martindsq ok I added Brazilian Portuguese in the project settings and sent a message to Andressa asking about Portuguese. In the meantime I think we can go ahead and merge this?

**Review by martindsq — APPROVED** [review]

**Pull request merged**
