### PR TITLE
Link changelog entries to GitHub issues starting with Unreleased

### PR DESCRIPTION
**Pull request by joshuatbrown**
## Issues covered
None

## Description
I'd love to have links to issues in the CHANGELOG. These will automatically go into our internal release notes to remove all ambiguity about which issue was addressed in a particular entry. And we could optionally choose to keep these in our external release notes to help our users to fully understand context. This may encourage our users who are developers to make open-source contributions to our app.

## How to test
Check out the CHANGELOG!

### CODE REVIEW

**Comment by pelumy** [comment]
@joshuatbrown, if the app is released to the store, will these links also show up there?

**Review by mplorentz — APPROVED** [review]
I am good with this, but let's wait to hear from all stakeholders first. I won't use it much personally but it only takes a few seconds to add and somebody will probably find it useful. I do think we should strip these links from the TestFlight/App Store release notes and keep them only here in Github. We should be able to modify our fastlane script to do that automatically sometime.

**Comment by joshuatbrown** [comment]
@pelumy Great question. I've thought about it some more, and I agree with Matt: we should not include the links in the TestFlight / App Store release notes. And yeah, modifying the fastlane script sounds like it would be nice and make this easier.

**Review by bryanmontz — APPROVED** [review]
Like others have said, I don't think it makes sense to show ticket links to App Store users, but traceability from the changelog to tickets is excellent. We'll need to consistently follow this format (or some format) for a script to remove them.

**Comment by joshuatbrown** [comment]
> traceability from the changelog to tickets is excellent. 

100% agreed. This is what I meant to say -- it helps _me_ to know what's in a build, what tickets to move from UAT to QA during a release. And it'll help Linda to much more easily do UAT and QA since she'll know exactly what tickets are in a build, instead of having to match our CHANGELOG line to a ticket.

> We'll need to consistently follow this format (or some format) for a script to remove them.

Indeed. I still expect to manually check the release notes before anything goes to TestFlight or, eventually, the App Store, but having the script do the work would be great.

**Review by martindsq — APPROVED** [review]

**Pull request merged**
