### PR TITLE
update following / follows / mutes to use the new AuthorCard design

### PR DESCRIPTION
**Pull request by rabble**

### CODE REVIEW

**Comment by martindsq** [comment]
I do like the new design. However, I think we can improve how we place the follow button, as it doesn't work well when the name is just a bit long.

IMG_0734

**Comment by rabble** [comment]
there a bug with this that prevents tapping in the author to see the profile. don’t merge or test until i fix this.

**Review by mplorentz — CHANGES_REQUESTED** [review]
marking this as needing changes so its status is clear in the PR list.

**Comment by mplorentz** [comment]
Closing this as it's been stale for three weeks.

**Pull request closed without merging**
