### PR TITLE
Automatic file uploads feature branch

### PR DESCRIPTION
**Pull request by boreq**
Opening this for visiblity.

### CODE REVIEW

**Comment by boreq** [comment]
I think we have now completed all the things that we still wanted to do here as documented by this issue:
- #490

**Comment by boreq** [comment]
Oh yeah for context this code was checked already, it is just up to deciding if this is ready to be merged to `main`.

**Comment by boreq** [comment]
https://github.com/planetary-social/nos/assets/1935975/31c327a4-97f6-499a-b144-cf7959072bb1

**Comment by mplorentz** [comment]
This is ready to merge! I found one minor issue but I will leave it in a comment on the ticket.

**Pull request merged**
