### PR TITLE
Disable "Post" button while media is uploading #1347

### PR DESCRIPTION
**Pull request by vien-eakar**
## Issues covered
fix bug : [1347](https://github.com/planetary-social/nos/issues/1347)

## Description
 I found that the isUploadingImage flag is set to true during image uploads. I have included this flag in the disable condition of the Post button.

## How to test
1. Navigate to Post then input message then upload image.
2. While Image uploading tap on Post button. Post button is disable.

## Screenshots/Video
Before fixed : https://github.com/user-attachments/assets/9c556393-4b68-4e2d-891b-0b68ea2bcfc4

After fixed : https://github.com/user-attachments/assets/d0cddb68-fcfe-4319-9601-990b0ab764c3

### CODE REVIEW

**Review by mplorentz — APPROVED** [review]
Thanks for the contribution @vien-eakar! This works perfectly! I went ahead and added a changelog entry for this. I think we just need you to sign the contributor license agreement (which allows us to change the license on the code in the future) and we'll be good to merge.

**Comment by vien-eakar** [comment]
@mplorentz  to sign to the contributor can I just add below comment.

**I have read the CLA Document and I hereby sign the CLA**

> Thanks for the contribution @vien-eakar! This works perfectly! I went ahead and added a changelog entry for this. I think we just need you to sign the contributor license agreement (which allows us to change the license on the code in the future) and we'll be good to merge.

**Comment by joshuatbrown** [comment]
@vien-eakar thanks again! It looks like our CLA Assistant bot is looking for a comment from your account that's attached to the commit which appears to be @NBViennv. Are you able to post a comment from that account to sign?

**Comment by NBViennv** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by joshuatbrown** [comment]
@vien-eakar it's merged! Thanks again for contributing!

**Comment by vien-eakar** [comment]
@joshuatbrown  You are welcome!

**Pull request merged**
