### PR TITLE
Add message to top of relays screen

### PR DESCRIPTION
**Pull request by joshuatbrown**
## Issues covered
#1218

## Description
Adds the "Important!" message to the top of the relays screen.

## How to test
1. Navigate to Relays
2. Observe message

## Screenshots/Video
| Before | After |
|--------|--------|
| Simulator Screenshot - iPhone 15 Pro - 2024-06-17 at 16 35 36 | Simulator Screenshot - iPhone 15 Pro - 2024-06-20 at 09 55 50 |

### CODE REVIEW

**Review by mplorentz — COMMENTED** [review]
This looks good, but can we horizontally align the text with the left edge of the containers? I know that's not what the screenshot in the ticket looks like, but Linda said the design was up to developer discretion, and that's how we have aligned inline text on the edit profile screen:
Simulator Screenshot - iPhone 15 - 2024-06-18 at 10 14 50

**Comment by mplorentz** [comment]
(I know the titles are aligned differently on the relays screen. The text still looks like it's floating too far to the right to me. We could move the titles too if it's easy.)

**Comment by joshuatbrown** [comment]
@mplorentz yeah, that's fine with me. I initially aligned the text with the section headers because that seemed more correct to me. Hopefully sliding those headers over to the left isn't too challenging and I can tackle that, too.

**Comment by joshuatbrown** [comment]
@mplorentz updated to fix that and a few other small design issues. I hope I didn't take it too far, but it was pretty quick to more closely match the recently redesigned Settings view.

**Review by mplorentz — APPROVED** [review]
Looks good, this is some nice touch up.

(I don't like that we have IMPORTANT in all caps, but that's what the ticket shows...)

**Comment by joshuatbrown** [comment]
@mplorentz I suppose we could make it not all caps and get Linda's thoughts.

**Review by mplorentz — APPROVED** [review]

**Pull request merged**
