### PR TITLE
localize follows notification #1446

### PR DESCRIPTION
**Pull request by bryanmontz**
## Issues covered
#1446 

## Description
Adds new localized strings to support localization of the follows push notifications. This change is only part of what's required to achieve the desired result, because the notifications will also need to be updated on the server side. I discussed this with @dcadenas, and he will be making the required server-side changes.

~~Unfortunately this can't truly be tested until the server-side changes are made, and these changes have no effect in the app until they are made.~~

Thanks to @mplorentz and @dcadenas for helping me test this!

Note: I wasn't able to use plural variants with the "You have x new followers!" string as I'd hoped. I tried initially and had "%i" for the wildcard, but when I tested it, the notification said only "@value@". The documentation for the "loc-args" key implies that you can only use strings:
> An array of strings containing replacement values for variables in your message text. Each %@ character in the string specified by loc-key is replaced by a value from this array. The first item in the array replaces the first instance of the %@ character in the string, the second item replaces the second instance, and so on.
https://developer.apple.com/documentation/usernotifications/generating-a-remote-notification

Screenshots:  
| one - no name | one with name | many |
| --- | --- | --- |
|IMG_8381|IMG_8379|IMG_8380|

### CODE REVIEW

**Review by joshuatbrown — COMMENTED** [review]
Looks good from a code perspective, but as you said, no way to test.

**Comment by dcadenas** [comment]
We should be able to test this with the push notifications test tool: https://icloud.developer.apple.com/dashboard/notifications/teams/GZCZBKH7MY/app/com.verse.Nos-dev/notifications/61c747f2-d8f2-4fcf-af7c-b777034782ad/environment/DEVELOPMENT/tracking/21b48cd5-6904-c5c6-5076-8c965c8b50e5

**Comment by dcadenas** [comment]
https://developer.apple.com/documentation/usernotifications/generating-a-remote-notification#2948651

**Comment by joshuatbrown** [comment]
Here's what I did to test this (since I don't see the steps documented anywhere):
1. Build and run the app on device
2. Set a breakpoint in `application(_:didRegisterForRemoteNotificationsWithDeviceToken:)`
3. printed `deviceToken.toHexString()` to the console
4. pasted that device token into the [Push Notifications test tool](https://icloud.developer.apple.com/dashboard/notifications/teams/GZCZBKH7MY/app/com.verse.Nos-dev/notifications)
5. Downloaded the JSON payload from [one of Bryan's test for localization](https://icloud.developer.apple.com/dashboard/notifications/teams/GZCZBKH7MY/app/com.verse.Nos-dev/notifications/28271aa7-c47e-44e1-93b4-679c467c3ab1/environment/DEVELOPMENT/tracking/248b68f0-cae7-996f-9c43-8339b7d1460c)
6. Put the app in the background
7. Send the notification from the Push Notifications console

**Review by joshuatbrown — APPROVED** [review]
Works for me!

**Comment by bryanmontz** [comment]
> Here's what I did to test this (since I don't see the steps documented anywhere):
> 
> 1. Build and run the app on device
> 2. Set a breakpoint in `application(_:didRegisterForRemoteNotificationsWithDeviceToken:)`
> 3. printed `deviceToken.toHexString()` to the console
> 4. pasted that device token into the [Push Notifications test tool](https://icloud.developer.apple.com/dashboard/notifications/teams/GZCZBKH7MY/app/com.verse.Nos-dev/notifications)
> 5. Downloaded the JSON payload from [one of Bryan's tests for localization](https://icloud.developer.apple.com/dashboard/notifications/teams/GZCZBKH7MY/app/com.verse.Nos-dev/notifications/28271aa7-c47e-44e1-93b4-679c467c3ab1/environment/DEVELOPMENT/tracking/248b68f0-cae7-996f-9c43-8339b7d1460c)
> 6. Put the app in the background
> 7. Send the notification from the Push Notifications console
> 8. Observe the notification on my device

Thanks for this, @joshuatbrown! I should've put this together. Sorry about that. I added these steps to a new documentation in Notion called How to Test Push Notifications.

**Pull request merged**
