### PR TITLE
Fix hang in ProfileView

### PR DESCRIPTION
**Pull request by martindsq**
ProfileView hangs consistently in my iPhone. But not after computing the unmuted events in a similar fashion to what we did in RepliesView.

### CODE REVIEW

**Review by mplorentz — COMMENTED** [review]
I think we need a similar change to the one made in #556, right?

**Comment by martindsq** [comment]
> I think we need a similar change to the one made in #556, right?

#556 is this one, but I got what you meant. Not exactly, but it is prone to the same problem of not getting some updates the user could make in the UI. I only found a problem with muting/unmuting the same profile the user is looking at

**Review by mplorentz — COMMENTED** [review]
I did some testing and found that new posts no longer show up right away when they are downloaded. Maybe we need an `.onChange(of: unmutedEvents)`?

**Review by mplorentz — APPROVED** [review]
Looks good!

**Pull request merged**
