### PR TITLE
prefer NIP-05 for Author webLink

### PR DESCRIPTION
**Pull request by bryanmontz**
## Issues covered
https://github.com/planetary-social/nos/issues/1227

## Description
Copying a link to a user's profile will now use the NIP-05 address and fall back to the user's npub if there is no NIP-05. It also adds a different special format for @nos.social NIP-05s.

## How to test
1. Navigate to a user's profile.
2. Tap the three dots button at top-right.
3. Tap the Copy Link button.
4. Paste it anywhere to see its contents.

Unit tests were added to cover the various cases.

### CODE REVIEW

**Comment by bryanmontz** [comment]
recheck

**Review by martindsq — APPROVED** [review]
I do like your suggestions and appreciate the unit tests you wrote. Great contribution! I'm approving this 🚢

**Comment by mplorentz** [comment]
Hey @bryanmontz thanks for the contribution! 

Unfortunately we've got two version of this CLA bot running concurrently. We added the new one and it looks like we didn't get the old one taken down properly :( I think you signed the old one. Can you try posting a comment with the text "I have read the CLA Document and I hereby sign the CLA" and see if that makes CI happy?

**Comment by bryanmontz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bryanmontz** [comment]
@mplorentz Okay it looks like the CLA step passed. Does something need to be added to the CHANGELOG?

**Comment by mplorentz** [comment]
@bryanmontz yes updating the changelog would be great! Those get posted as TestFlight release notes for end users.

**Comment by bryanmontz** [comment]
Done. 👍

**Comment by joshuatbrown** [comment]
@bryanmontz thanks for contributing! I'm glad we have this now!

**Pull request merged**
