### PR TITLE
Color assets moved to Colors.xcassets; swiftgen.yml updated to reflect change

### PR DESCRIPTION
**Pull request by lingoslinger**
Issue: Create Colors.xcassets and move existing colors to it
#1374 

Changes:
- Added Colors.xcassets
- moved existing color assets to the new asset catalog and deleted Colors folder in Assets,xcassets
- modified swiftgen config file to reflect this change

Testing:
- observe that nothing has visually changed, and that there are no errors related to use of the color assets

Additional notes:
- planning to add some tests verifying the existence of colors while working on [1375](https://github.com/planetary-social/nos/issues/1375)

### CODE REVIEW

**Comment by lingoslinger** [comment]
recheck

**Comment by lingoslinger** [comment]
recheck

**Comment by lingoslinger** [comment]
> It looks like maybe the new Colors.xcassets wasn't added to the Xcode project file, or maybe that file was just missed in your commit. Would you mind adding it? Otherwise, this looks great!

That was a self own, I failed to commit the changes to the .proj file in my previous commits, should be fixed now!

**Review by joshuatbrown — CHANGES_REQUESTED** [review]
@lingoslinger The app is running great now and looks good. I'm still seeing the error when running the tests, which is due to our somewhat unique test setup. It looks like you'll need to add `Colors.xcassets` to the NosTests target as well, and I think that'll fix the issue. Thanks again!

**Comment by lingoslinger** [comment]
sorry I missed this Josh, I am on the case right now.

**Review by joshuatbrown — APPROVED** [review]
@lingoslinger thanks again -- this is perfect! Merging now! 🚀

**Pull request merged**
