### PR TITLE
Stop deleting / purging mute lists

### PR DESCRIPTION
**Pull request by rabble**
This i an attempt at preventing mute lists from being reset... i'm not sure if it actually works.

### CODE REVIEW

**Comment by rabble** [comment]
This does not fix the mute lists getting overwritten bug.

**Comment by mplorentz** [comment]
Looks like I fixed it. I just added a condition to keep all the user's own notes from being deleted. We used to have this condition and I think I removed it to try to get the average database size down, but I don't really think people have that many events... maybe I'm wrong, I'll keep an eye on the [Posthog report](https://posthog.planetary.tools/insights/SIEKZrGQ).

@martindsq or @rabble could you give my changes a review?

**Comment by mplorentz** [comment]
This commit actually crashes on launch. I know I tested this after coding it so I'm very confused why it wasn't crashing for me before. The only thing I can think is that Xcode 15 has sometimes been running an old version of the app even after the build fails so I end up not testing the latest code. Anyway I'm pushing up a fix now.

**Comment by mplorentz** [comment]
Going to go ahead and merge since this has been deployed.

**Pull request merged**
