### PR TITLE
feature/nos152-nip05-search-bar-and-edit-profile

### PR DESCRIPTION
**Pull request by jcswift23**
https://github.com/planetary-social/nos/issues/152
NIP05 tap on the profile page opens the domain.
You can search in the Discover search bar by NIP05.
You can edit the NIP05 in the edit profile screen.

### CODE REVIEW

**Comment by jcswift23** [comment]
https://user-images.githubusercontent.com/125296686/225329515-b8f6ed87-b97f-4f2a-a504-4f1db1b46062.mov

**Review by mplorentz — COMMENTED** [review]
Nice work! A few tweaks I would like to see:
- Can we change the placeholder text in the discover search bar to "Find a user by ID or NIP-05". A little wordy but it gets the point across.
- Can you disable autocorrection on the Discover search bar?
- If the verification on a NIP-05 fails let's display it on the user's profile with a strikethrough. I set a fake one on my own profile and was briefly confused why it didn't show up.

**Comment by jcswift23** [comment]
https://user-images.githubusercontent.com/125296686/225367299-3204c180-76a4-4c63-90c3-dc38d0b72e6f.mov

Here is the latest with updates.

**Review by mplorentz — APPROVED** [review]
This looks ready to merge to me once the SwiftLint errors are fixed. I pushed one commit because it looks like your changes to `Event+CoreDataClass.swift` were clobbered by your latest merge from main.

**Pull request merged**
