### PR TITLE
Fix issue where Report user menu isn’t visible on iPad

### PR DESCRIPTION
**Pull request by joshuatbrown**
## Issues covered
#868

## Description
Fixes the issue where the Flag this User menu isn't visible on iPad.

## How to test
1. Navigate to a profile
2. Tap the three dots in the upper right
3. Tap Flag this user
4. Observe confirmation dialog near middle of screen

## Screenshots/Video

https://github.com/planetary-social/nos/assets/59564/f8200905-d788-4a16-91c3-dc628b7f38f4

### CODE REVIEW

**Review by mplorentz — COMMENTED** [review]
This doesn't show the menu if you scroll the ProfileHeader out of view and then tap to Flag this user. Can we put the reportMenu on the ellipsis button?

**Comment by joshuatbrown** [comment]
@mplorentz I did try that, but it sounds like that didn't work based on my [comment](https://github.com/planetary-social/nos/issues/868#issuecomment-2176795989) on the ticket. I'll try again, though, just to make sure. I assume this is because of the timing of dismissing the first popover from that button, so maybe we could add a delay. But I absolutely despise using delays, so even suggesting that is painful... 😞

**Comment by joshuatbrown** [comment]
@mplorentz ignore that. I just tried it again from the ellipsis button and it worked. 🤦

**Review by mplorentz — APPROVED** [review]
This works for me on Mac, iPad, and iPhone now. I did run into https://github.com/planetary-social/nos/issues/1145 and found some steps to kind of reproduce. But I can reproduce on Staging as well.

**Pull request merged**
