### PR TITLE
Update CHANGELOG format for easier release notes

### PR DESCRIPTION
**Pull request by joshuatbrown**
## Issues covered
None

## Description
In order to make it easier to create release notes for TestFlight, @bryanmontz suggested tagging entries in the CHANGELOG. Together, we settled on `[skip-release-notes]` at the end of each line that should not appear in the TestFlight release notes. I'm proposing we remove the need to duplicate this string in each line of the CHANGELOG that should not appear in the TestFlight release notes by using headings instead. I'm still not 100% sure what those headings should be, but this PR has my best thoughts at the moment.

This is a continuation of the discussion in https://github.com/planetary-social/nos/pull/1423#discussion_r1734511906

### CODE REVIEW

**Review by martindsq — APPROVED** [review]

**Comment by joshuatbrown** [comment]
@mplorentz @bryanmontz Before I merge, I'd like to get your thoughts on this since it impacts our process to some degree.

**Review by mplorentz — APPROVED** [review]
Works for me!

**Comment by bryanmontz** [comment]
Yeah, I think headings works too. Might prevent some conflicts as well. But do "internal" changes go into releases? Will there be a public/internal distinction in each release?

**Comment by joshuatbrown** [comment]
> But do "internal" changes go into releases?

@bryanmontz yeah, all changes go into all releases at this point. We just don't need to tell our users that we organized our colors into Colors.xcassets instead of using `Color(hex:)`, for example, so that's the purpose of the "internal" section. Notes that we still want to know as devs but that nobody else cares about.

> Will there be a public/internal distinction in each release?

Yes, I'd expect each release in our CHANGELOG to have these two sections.

**Comment by joshuatbrown** [comment]
I think we'll want staging builds to have _all_ notes because there are a few things Linda will want to see, like "Included the npub in the properties list sent to analytics." and "Added a feature flag toggle for “Enable new media display” to Staging builds.". But then our release builds should have just the "Release Notes" section. So when we get around to automating this, I think those are the specs we'll want to implement.

**Comment by joshuatbrown** [comment]
Here's the ticket for those changes: https://github.com/planetary-social/nos/issues/1442

**Pull request merged**
