### PR TITLE
Update recommended relays list

### PR DESCRIPTION
**Pull request by martindsq**
## Issues covered
#1212 

## Description
I updated the list of recommended relays. I checked that when creating an account, only these four relays are added initially. However, I don't understand what the allKnown list is for, @mplorentz can you explain that. For some reason, my test account ended with all those relays after using Nos for a while. Should I update that list as well?

## How to test
1. Create a new account
2. Go the the relays screen
3. Check the list

### CODE REVIEW

**Review by joshuatbrown — APPROVED** [review]
Works as expected! Does the order here matter? Perhaps Linda was specifying the order she'd like to see them, but I don't know.

**Comment by joshuatbrown** [comment]
Personally, I'd love to see relay.nos.social at the top of the list but I'm not sure that's a blocker.

**Comment by martindsq** [comment]
> Personally, I'd love to see relay.nos.social at the top of the list but I'm not sure that's a blocker.

I think that's a good idea

**Review by joshuatbrown — COMMENTED** [review]
Didn't realize you'd need to write a sort function, so sorry for adding that work to the scope, but hey, this is great! Could we also use it in the RECOMMENDED RELAYS section for consistency?

**Comment by mplorentz** [comment]
@martindsq 
> However, I don't understand what the allKnown list is for, @mplorentz can you explain that. 

The `allKnown` relays are the ones we connect to when we don't have a relay list for the current user (or they have removed all relays from their list). You can see the logic for that in `RelayService.subscribeToEvents(matching:from:)`.

> For some reason, my test account ended with all those relays after using Nos for a while. 

That sounds like a pretty bad bug! Did it actually publish your relay list with those relays in it? Or did you just see them in the logs? I think we leave the websocket connections to these relays open even after we successfully get the user's relay list, but we stop sending new REQs to them. But if somehow that is overwriting the user's list then that is very bad. We may need to reopen #1213. 

> Should I update that list as well?

It probably could use a refresh but we want to keep it large so we have a good chance of finding the user's data on login... Glancing at the current list it still includes most of the big relays so let's just leave it for now.

**Comment by martindsq** [comment]
I merged the latest changes from main and fixed the conflicts.

> Didn't realize you'd need to write a sort function, so sorry for adding that work to the scope, but hey, this is great! Could we also use it in the RECOMMENDED RELAYS section for consistency?

Well thought, I pushed a commit that addresses that and re-requested a review from you. @joshuatbrown 

@mplorentz thanks for the in-depth explanation. It happened while using a test account in nos-dev, I don't see it anymore. I'll keep my eyes open and re-open that issue if I see that happening again.

**Review by joshuatbrown — APPROVED** [review]
Excellent!

**Pull request merged**
