### PR TITLE
NOS45 - Preload sample data

### PR DESCRIPTION
**Pull request by cjorgensen**
- Adds a "Load Sample Data" button in Settings for DEBUG builds
- Removes Lorentz metadata where information was incomplete
- Updates Follow buttons to use localized strings

### CODE REVIEW

**Comment by mplorentz** [comment]
I went a different direction with some changes to the Follow model in #54. I'm a little biased, but I think I like my changes better, because we get a little bit stricter typing with `Follow.source` and `Follow.destination` both pointing directly to `Authors`, instead of just having `pubKey` be a string. But I'm curious what you think and I'm happy to huddle about this if you want to talk it through.

**Comment by cjorgensen** [comment]
> I went a different direction with some changes to the Follow model in #54. I'm a little biased, but I think I like my changes better, because we get a little bit stricter typing with `Follow.source` and `Follow.destination` both pointing directly to `Authors`, instead of just having `pubKey` be a string. But I'm curious what you think and I'm happy to huddle about this if you want to talk it through.

[#54](https://github.com/planetary-social/nos/pull/54) looks good. I can merge those changes into this one or, if need be, close this PR and reapply the data loading parts in a new PR.

**Comment by mplorentz** [comment]
Ok thanks. I went ahead and merged #54 to `main` and created all the conflicts 😬 if you want help resolving anything hmu.

**Review by jcswift23 — APPROVED** [review]

**Comment by jcswift23** [comment]
LoadSampleData1
LoadSampleData2
Looks good!

**Comment by jcswift23** [comment]
I clicked on "Load Sample Data" from Settings, then went back to the Home Feed and it will only display the Sample data.

**Pull request merged**
